update

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,5 +1,117 @@
 #!/bin/bash
 
+
+
+function copyFragment() {
+
+    sourceFragmentDir=$1
+    if [ -z "${sourceFragmentDir}" ]; then
+        echo "Error: $0[${LINENO}]"
+        echo "No sourceFragmentDir argument supplied"
+        exit 1
+    fi
+
+    targetFragmentsDir=$2
+    if [ -z "${targetFragmentsDir}" ]; then
+        echo "Error: $0[${LINENO}]"
+        echo "No targetFragmentsDir argument supplied"
+        exit 1
+    fi
+
+    # Check the sourceFragmentDir directory exists
+    if [ ! -d "${sourceFragmentDir}" ]; then
+        echo "Error: $0[${LINENO}]"
+        echo "result: ${result}"
+        echo "directory not found: ${sourceFragmentDir}"
+        exit 1
+    fi
+
+    # Check the target directory exists
+    if [ ! -d "${targetFragmentsDir}" ]; then
+        echo "Error: $0[${LINENO}]"
+        echo "result: ${result}"
+        echo "directory not found: ${targetFragmentsDir}"
+        exit 1
+    fi
+
+    basename=$(basename, ${sourceFragmentDir})
+    extension="${basename##*.}"
+    filename="${basename%.*}"
+    targetFragmentDir="${targetFragmentsDir}/${filename}"
+
+    # Copy the sourceFragmentDir dir to the output directory
+    if [ ! -d "${targetFragmentDir}" ]; then
+        echo "updating: ${targetFragmentDir}"
+        mkdir -p "${targetFragmentDir}"
+        result=$?
+        if [ ! ${result} -eq 0 ]; then
+            echo "Error: $0[${LINENO}]"
+            echo "result: ${result}"
+            echo "targetFragmentDir: ${targetFragmentDir}"
+            exit 1
+        fi
+    fi
+
+    src="${sourceFragmentDir}/fragment.html"
+    trg="${targetFragmentDir}/fragment.html"
+    if [ "${trg}" -nt "${src}" ]; then
+        : # echo "up-to-date: ${trg}"
+    else
+        echo "updating: ${targetFragmentDir}"
+        cp -r "${src}" "${trg}"
+        result=$?
+        if [ ! ${result} -eq 0 ]; then
+            echo "Error: $0[${LINENO}]"
+            echo "result: ${result}"
+            echo "src: ${src}"
+            echo "trg: ${trg}"
+            exit 1
+        fi
+    fi
+
+    src="${sourceFragmentDir}/fragment.json"
+    trg="${targetFragmentDir}/fragment.json"
+    if [ "${trg}" -nt "${src}" ]; then
+        : # echo "up-to-date: ${trg}"
+    else
+        echo "updating: ${targetFragmentDir}"
+        cp -r "${src}" "${trg}"
+        result=$?
+        if [ ! ${result} -eq 0 ]; then
+            echo "Error: $0[${LINENO}]"
+            echo "result: ${result}"
+            echo "src: ${src}"
+            echo "trg: ${trg}"
+            exit 1
+        fi
+    fi
+
+    # Output the dependancies
+    year=$(jq '.year' "${fragment}/fragment.json")
+    result=$?
+    if [ ! ${result} -eq 0 ]; then
+        echo "Error: $0[${LINENO}]"
+        echo "result: ${result}"
+        echo "${stdout}"
+        echo "sourceFragmentDir: ${sourceFragmentDir}"
+        exit 1
+    fi
+
+    makefile="output/temp/${year}.mk"
+    if [ ! -f "${makefile}" ]; then
+        printf "${year}.html : " > ${makefile}
+    fi
+    printf "\\\n    ${targetFragmentDir}/fragment.html" >> ${makefile}
+    printf "\\\n    ${targetFragmentDir}/fragment.json" >> ${makefile}
+    printf "\\\n    ${imageTarget}" >> ${makefile}
+}
+
+
+
+
+
+
+
 root="/media/NAS/photo/documents/sea-captains-chest"
 
 dirs=()
@@ -95,7 +207,7 @@ for i in "${dirs[@]}"; do
                     exit 1
                 fi
             else
-                # Call the java extract program (which will also generate a makefile for next time round)
+                # Call the 'java' extract program
                 ./extract "${file}"
                 result=$?
                 if [ ! ${result} -eq 0 ]; then
@@ -114,75 +226,42 @@ for i in "${dirs[@]}"; do
         basename=$(basename "${file}")
 
         regx="^img([0-9]{4})-image-.*\.(jpg|png)$"
-        if [[ "${basename}" =~ ${regx} ]]; then
+        if [[ ! "${basename}" =~ ${regx} ]]; then
+            continue
+        fi
 
-            # Copy the images to the html images directory
-            imageSource=${file}
-            imageTarget="output/html/images/${basename}"
-            if [ "${imageTarget}" -nt "${imageSource}" ]; then
-                : # echo "up-to-date: ${imageTarget}"
-            else
-                echo "updating: ${imageTarget}"
-                cp "${imageSource}" "${imageTarget}"
-            fi
-
-            extension="${basename##*.}"
-            filename="${basename%.*}"
-
-            # Check the image fragment exists
-            fragment="${root}/${i}/metadata/fragments/${filename}"
-            if [ ! -d "${fragment}" ]; then
-                echo "Error: $0[${LINENO}]"
-                echo "result: ${result}"
-                echo "missing fragment for image file: ${fragment}"
-                exit 1
-            fi
-
-            # Copy the image fragment dir to the output directory
-            target="output/fragments/${filename}"
-            if [ "${target}" -nt "${fragment}" ]; then
-                : # echo "up-to-date: ${target}"
-            else
-                echo "updating: ${target}"
-                mkdir -p "${target}"
-            fi
-
-            src="${fragment}/fragment.html"
-            trg="${target}/fragment.html"
-            if [ "${trg}" -nt "${src}" ]; then
-                : # echo "up-to-date: ${trg}"
-            else
-                echo "updating: ${target}"
-                cp -r "${src}" "${trg}"
-            fi
-
-            src="${fragment}/fragment.json"
-            trg="${target}/fragment.json"
-            if [ "${trg}" -nt "${src}" ]; then
-                : # echo "up-to-date: ${trg}"
-            else
-                echo "updating: ${target}"
-                cp -r "${src}" "${trg}"
-            fi
-
-            # Output the dependancies
-            year=$(jq '.year' "${fragment}/fragment.json")
+        # Copy the images to the html images directory
+        imageSource=${file}
+        imageTarget="output/html/images/${basename}"
+        if [ "${imageTarget}" -nt "${imageSource}" ]; then
+            : # echo "up-to-date: ${imageTarget}"
+        else
+            echo "updating: ${imageTarget}"
+            cp "${imageSource}" "${imageTarget}"
             result=$?
             if [ ! ${result} -eq 0 ]; then
                 echo "Error: $0[${LINENO}]"
                 echo "result: ${result}"
-                echo "${stdout}"
-                echo "fragment: ${fragment}"
+                echo "imageSource: ${imageSource}"
+                echo "imageTarget: ${imageTarget}"
                 exit 1
             fi
+        fi
 
-            makefile="output/temp/${year}.mk"
-            if [ ! -f "${makefile}" ]; then
-                printf "${year}.html : " > ${makefile}
-            fi
-            printf "\\\n    ${target}/fragment.html" >> ${makefile}
-            printf "\\\n    ${target}/fragment.json" >> ${makefile}
-            printf "\\\n    ${imageTarget}" >> ${makefile}
+        extension="${basename##*.}"
+        filename="${basename%.*}"
+
+        # Copy the image fragments
+        sourceFragmentDir="${root}/${i}/metadata/fragments/${filename}"
+        targetFragmentsDir="./output/fragments/"
+        copyFragment "${sourceFragmentDir}" "${targetFragmentsDir}"
+        result=$?
+        if [ ! ${result} -eq 0 ]; then
+            echo "Error: $0[${LINENO}]"
+            echo "result: ${result}"
+            echo "sourceFragmentDir: ${sourceFragmentDir}"
+            echo "targetFragmentsDir: ${targetFragmentsDir}"
+            exit 1
         fi
     done
 done
@@ -191,12 +270,15 @@ done
 for makefile in "output/temp/"*; do
     printf "\n" >> ${makefile}
 
-    cp ${makefile} "output/dependancies/"
+    src="${makefile}"
+    trg="${output/dependancies/}"
+    cp "${src}" "${trg}"
     result=$?
     if [ ! ${result} -eq 0 ]; then
         echo "Error: $0[${LINENO}]"
         echo "result: ${result}"
-        echo "${stdout}"
+        echo "src: ${src}"
+        echo "trg: ${trg}"
         exit 1
     fi
 done
@@ -204,21 +286,24 @@ done
 #-------------------------------------------
 # Copy the manually crafted fragments 
 #-------------------------------------------
-for i in "${dirs[@]}"; do
-    source="${root}/${i}/metadata/fragments"/*
-    target="output/fragments/"
-    cp -r ${source} ${target} 1>/dev/null 2>/dev/null
-    result=$?
-    if [ ${result} -eq 0 ]; then
-        : # ok
-    elif [ ${result} -eq 1 ]; then
-        : # ok
-    else
-        echo "Error: $0[${LINENO}]"
-        echo "result: ${result}"
-        echo "${stdout}"
-        exit 1
-    fi
+for diary in "${dirs[@]}"; do
+
+    for fragment in "${root}/${diary}/metadata/fragments"/*; do
+        [ -d "${fragment}" ] || continue
+
+        # Copy the image fragments
+        sourceFragmentDir="${fragment}"
+        targetFragmentsDir="./output/fragments/"
+        copyFragment "${sourceFragmentDir}" "${targetFragmentsDir}"
+        result=$?
+        if [ ! ${result} -eq 0 ]; then
+            echo "Error: $0[${LINENO}]"
+            echo "result: ${result}"
+            echo "sourceFragmentDir: ${sourceFragmentDir}"
+            echo "targetFragmentsDir: ${targetFragmentsDir}"
+            exit 1
+        fi
+    done
 done
 
 #-------------------------------------------
@@ -239,7 +324,8 @@ for file in input/styles/*; do
         if [ ! ${result} -eq 0 ]; then
             echo "Error: $0[${LINENO}]"
             echo "result: ${result}"
-            echo "${stdout}"
+            echo "file: ${file}"
+            echo "target: ${target}"
             exit 1
         fi
     fi
@@ -253,6 +339,5 @@ result=$?
 if [ ! ${result} -eq 0 ]; then
     echo "Error: $0[${LINENO}]"
     echo "result: ${result}"
-    echo "${stdout}"
     exit 1
 fi
