update

diff --git a/build b/build
--- a/build
+++ b/build
@@ -15,65 +15,10 @@ dirs+=('diary-1838')
 dirs+=('diary-1839')
 
 
-function extractText {
-
-    inputFilename=${1}
-    if [ -z "${inputFilename}" ]; then
-        echo "Error: $0[${LINENO}]"
-        echo "missing inputFilename argument"
-        exit 1
-    fi
-
-    if [ ! -f "${inputFilename}" ]; then
-        echo "Error: $0[${LINENO}]"
-        echo "file not found: \"${inputFilename}\""
-        exit 1
-    fi
-
-    basename=$(basename "${inputFilename}" ".docx")
-    dependancyfile="./output/dependancies/${basename}"
-
-    if [ "${dependancyfile}" -nt "${inputFilename}" ]; then
-        : # echo "page up-to-date: ${dependancyfile}"
-    else
-        echo "generating page: ${dependancyfile}"
-
-        java -cp ${classpath} com.rsmaxwell.extractor.App --inputFile "${inputFilename}" 1>temp/stdout.txt 2>temp/stderr.txt
-        result=$?
-        if [ ! ${result} -eq 0 ]; then
-            echo "Error: $0[${LINENO}]"
-            echo "result: ${result}"
-            echo "${inputFilename}"
-            echo "----[ stdout ]--------------------------"
-            cat temp/stdout.txt
-            echo "----[ stderr ]--------------------------"
-            cat temp/stderr.txt
-            echo "----------------------------------------"
-            exit 1
-        fi
-    fi
-}
-
-
-
 REPOSITORYURL="https://server.rsmaxwell.co.uk/archiva/repository"
 REPOSITORYID="releases"
 REPOSITORY="releases"
 GROUPID="com.rsmaxwell.diary"
-
-ARTIFACTID="extractor"
-
-# find the latest version of the extractor jar
-stdout=$(./getLatestJar "${REPOSITORYURL}" "${REPOSITORYID}" "${REPOSITORY}" "${GROUPID}" "${ARTIFACTID}")
-result=$?
-if [ ${result} -eq 0 ]; then
-    extractorJar=${stdout}
-else
-    echo "Error: $0[${LINENO}]"
-    echo "result: ${result}"
-    echo "${stdout}"
-    exit 1
-fi
 
 ARTIFACTID="diaryjson"
 
@@ -297,7 +242,7 @@ for i in "${dirs[@]}"; do
                 make --file "${makefile}"
             else
                 # Call the java extract program (which will also generate a makefile)
-                extractText "${file}"
+                call extract "${file}"
                 result=$?
                 if [ ! ${result} -eq 0 ]; then
                     echo "Error: $0[${LINENO}]"
@@ -395,23 +340,39 @@ for file in styles/*.css; do
 done
 
 
-echo "generate PDF diaries from the day files (*.json)"
+#-------------------------------------------
+# Check, clear and make directories 
+#-------------------------------------------
+if [ ! -d "${root}" ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "root not found: [${root}]"
+    exit 1
+fi
 
-classpath="${generatorJar}:${diaryjsonJar}:${commonsCliJar}:${jacksonDataBindJar}:${jacksonCoreJar}:${jacksonAnnotationsJar}"
-classpath="${classpath}:${itextpdfJar}:${itextpdfFormsJar}:${itextpdfKernelJar}:${itextpdfIOJar}:${itextpdfLayoutJar}:${itextpdfSvgJar}:${itextpdfStyledXmlParserJar}"
-classpath="${classpath}:${slf4jJar}"
-
-java -cp ${classpath} com.rsmaxwell.generator.App --inputDir data --outputDir output 1>temp/stdout.txt 2>temp/stderr.txt
+rm -rf temp
 result=$?
 if [ ! ${result} -eq 0 ]; then
     echo "Error: $0[${LINENO}]"
     echo "result: ${result}"
-    echo "${inputFilename}"
-    echo "----[ stdout ]--------------------------"
-    cat temp/stdout.txt
-    echo "----[ stderr ]--------------------------"
-    cat temp/stderr.txt
-    echo "----------------------------------------"
     exit 1
 fi
 
+mkdir -p "output/html/images" "output/fragments" "temp"
+result=$?
+if [ ! ${result} -eq 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    exit 1
+fi
+
+#-------------------------------------------
+# Check, clear and make directories 
+#-------------------------------------------
+call generate
+result=$?
+if [ ! ${result} -eq 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    echo "${stdout}"
+    exit 1
+fi
