generate each year separatly

diff --git a/build b/build
--- a/build
+++ b/build
@@ -339,13 +339,17 @@ done
 #-------------------------------------------
 # Generate the HTML documents from the fragments 
 #-------------------------------------------
-./generate input/templates output
-result=$?
-if [ ! ${result} -eq 0 ]; then
-    echo "Error: $0[${LINENO}]"
-    echo "result: ${result}"
-    exit 1
-fi
+for year in output/*; do
+    [ -f "${year}" ] || continue
+
+    ./generate input/templates output year
+    result=$?
+    if [ ! ${result} -eq 0 ]; then
+        echo "Error: $0[${LINENO}]"
+        echo "result: ${result}"
+        exit 1
+    fi
+done
 
 #-------------------------------------------
 # Generate an index.html pointing to the diaries
diff --git a/generate b/generate
--- a/generate
+++ b/generate
@@ -9,7 +9,7 @@ fi
 
 if [ ! -d "${templatesDir}" ]; then
     echo "Error: $0[${LINENO}]"
-    echo "file not found: \"${templatesDir}\""
+    echo "dir not found: \"${templatesDir}\""
     exit 1
 fi
 
@@ -23,9 +23,24 @@ fi
 
 if [ ! -d "${outputDir}" ]; then
     echo "Error: $0[${LINENO}]"
-    echo "file not found: \"${outputDir}\""
+    echo "dir not found: \"${outputDir}\""
     exit 1
 fi
+
+
+year=${3}
+if [ -z "${outputDir}" ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "missing year argument"
+    exit 1
+fi
+
+if [ ! -d "${outputDir}/${year}" ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "dir not found: \"${outputDir}/${year}\""
+    exit 1
+fi
+
 
 
 
@@ -232,7 +247,7 @@ classpath="${classpath}:${jacksonDataBindJar}:${jacksonCoreJar}:${jacksonAnnotat
 classpath="${classpath}:${itextpdfJar}:${itextpdfFormsJar}:${itextpdfKernelJar}:${itextpdfIOJar}:${itextpdfLayoutJar}:${itextpdfSvgJar}:${itextpdfStyledXmlParserJar}"
 classpath="${classpath}:${slf4jApiJar}:${slf4jSimpleJar}"
 
-java -cp ${classpath} com.rsmaxwell.generator.App --templates ${templatesDir} --output ${outputDir}  1>temp/stdout.txt 2>temp/stderr.txt
+java -cp ${classpath} com.rsmaxwell.generator.App --templates ${templatesDir} --output ${outputDir} --year ${year} 1>temp/stdout.txt 2>temp/stderr.txt
 result=$?
 if [ ! ${result} -eq 0 ]; then
     echo "Error: $0[${LINENO}]"
