add the diary as an argument

diff --git a/build b/build
--- a/build
+++ b/build
@@ -155,7 +155,7 @@ if [ ! ${result} -eq 0 ]; then
     exit 1
 fi
 
-mkdir -p "output/html/images" "output/html/css" "output/fragments" "temp"
+mkdir -p "output/html/images" "output/html/css" "output/html/controls" "output/fragments" "temp"
 result=$?
 if [ ! ${result} -eq 0 ]; then
     echo "Error: $0[${LINENO}]"
@@ -287,6 +287,31 @@ for file in input/styles/*; do
     basename=$(basename "${file}")
 
     target="output/html/css/${basename}"
+    if [ "${target}" -nt "${file}" ]; then
+        : # echo "up-to-date: ${target}"
+    else
+        echo "updating: ${target}"
+        cp "${file}" "${target}"
+        result=$?
+        if [ ! ${result} -eq 0 ]; then
+            echo "Error: $0[${LINENO}]"
+            echo "result: ${result}"
+            echo "file: ${file}"
+            echo "target: ${target}"
+            exit 1
+        fi
+    fi
+done
+
+#-------------------------------------------
+# Copy the control images
+#-------------------------------------------
+for file in input/controls/*; do
+    [ -f "${file}" ] || continue
+
+    basename=$(basename "${file}")
+
+    target="output/html/controls/${basename}"
     if [ "${target}" -nt "${file}" ]; then
         : # echo "up-to-date: ${target}"
     else
