replace special chars with htmp4 entities

diff --git a/extract b/extract
--- a/extract
+++ b/extract
@@ -74,6 +74,18 @@ else
     exit 1
 fi
 
+# get the ApacheCommonsLang3 Jar
+stdout=$(./getJar "org.apache.commons" "commons-lang3" "3.9" )
+result=$?
+if [ ${result} -eq 0 ]; then
+    apacheCommonsLang3Jar=${stdout}
+else
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    echo "${stdout}"
+    exit 1
+fi
+
 # get the JacksonDatabind Jar
 stdout=$(./getJar "com.fasterxml.jackson.core" "jackson-databind" "2.10.2")
 result=$?
@@ -139,7 +151,7 @@ fi
 # Extract html fragments from the word file
 #-------------------------------------------
 classpath="${extractorJar}:${diaryjsonJar}"
-classpath="${classpath}:${apacheCommonsCliJar}:${apacheCommonsTextJar}"
+classpath="${classpath}:${apacheCommonsCliJar}:${apacheCommonsTextJar}:${apacheCommonsLang3Jar}"
 classpath="${classpath}:${jacksonDataBindJar}:${jacksonCoreJar}:${jacksonAnnotationsJar}"
 classpath="${classpath}:${slf4jApiJar}:${slf4jSimpleJar}"
 
