reduce number of args to extract

diff --git a/extract b/extract
--- a/extract
+++ b/extract
@@ -1,40 +1,11 @@
 #!/bin/bash
 
-rootDir=${1}
-if [ -z "${rootDir}" ]; then
-    echo "Error: $0[${LINENO}]"
-    echo "missing rootDir argument"
-    exit 1
-fi
-
-if [ ! -d "${rootDir}" ]; then
-    echo "Error: $0[${LINENO}]"
-    echo "directory not found: \"${rootDir}\""
-    exit 1
-fi
-
-diary=${2}
-if [ -z "${diary}" ]; then
-    echo "Error: $0[${LINENO}]"
-    echo "missing diary argument"
-    exit 1
-fi
-
-word=${3}
+word=${1}
 if [ -z "${word}" ]; then
     echo "Error: $0[${LINENO}]"
     echo "missing word argument"
     exit 1
 fi
-
-imageFile=${4}
-if [ -z "${imageFile}" ]; then
-    echo "Error: $0[${LINENO}]"
-    echo "missing imageFile argument"
-    exit 1
-fi
-
-
 
 REPOSITORYURL="https://server.rsmaxwell.co.uk/archiva/repository"
 REPOSITORYID="releases"
@@ -166,29 +137,72 @@ else
 fi
 
 
+root=$(jq -r '.root' "${HOME}/diary.json")
+result=$?
+if [ ! ${result} -eq 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    exit 1
+fi
+
+diary=$(jq -r '.diary' "${HOME}/diary.json")
+result=$?
+if [ ! ${result} -eq 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    exit 1
+fi
+
+wordFile="${root}/${diary}/metadata/word/${word}"
+if [ ! -f "${wordFile}" ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "file not found: ${wordFile}"
+    exit 1
+fi
+
+regex="img([0-9]{4})(-(left|right))?.docx"
+if [[ ! "${word}" =~ ${regex} ]]; then
+    echo "Error: $0[${LINENO}]"
+    echo "wordfilename does not match pattern: ${word}"
+    exit 1
+fi
+
+number="${BASH_REMATCH[1]}"
+image="img${number}.jpg"
+imageFile="${root}/${diary}/${image}"
+if [ ! -f "${imageFile}" ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "file not found: ${imageFile}"
+    exit 1
+fi
 
 # Extract html fragments from the word file
 
 if [[ "$OSTYPE" == "cygwin" ]]; then
     SEP=";"
-    rootDirJava=$(cygpath -w "${rootDir}")
+    rootJava=$(cygpath -w "${root}")
 else
     SEP=":"
-    rootDirJava=${rootDir}
+    rootJava=${root}
 fi
+
+echo "root:  ${root}"
+echo "diary: ${diary}"
+echo "word:  ${word}"
+echo "image: ${image}"
 
 classpath="${extractorJar}${SEP}${diaryjsonJar}"
 classpath="${classpath}${SEP}${apacheCommonsCliJar}${SEP}${apacheCommonsTextJar}${SEP}${apacheCommonsLang3Jar}"
 classpath="${classpath}${SEP}${jacksonDataBindJar}${SEP}${jacksonCoreJar}${SEP}${jacksonAnnotationsJar}"
 classpath="${classpath}${SEP}${slf4jApiJar}${SEP}${slf4jSimpleJar}"
 
-java -cp ${classpath} com.rsmaxwell.extractor.App --root "${rootDirJava}" --diary "${diary}" --word "${word}" --image "${imageFile}"
+java -cp ${classpath} com.rsmaxwell.extractor.App --root "${rootJava}" --diary "${diary}" --word "${word}" --image "${image}"
 result=$?
 if [ ! ${result} -eq 0 ]; then
     echo "Error: $0[${LINENO}]"
     echo "result: ${result}"
-    echo "rootDir: ${rootDir}"
-    echo "rootDirJava: ${rootDirJava}"
+    echo "root: ${root}"
+    echo "rootJava: ${rootJava}"
     echo "diary: ${diary}"
     echo "imageFile: ${imageFile}"
     exit 1
