discribe usage in readme

diff --git a/formatFragment b/formatFragment
--- a/formatFragment
+++ b/formatFragment
@@ -20,7 +20,7 @@ if [ ! -f "${fragment_json}" ]; then
     exit 1
 fi
 
-stylesheet="input/styles/diary.css"
+stylesheet="input/html/css/diary.css"
 if [ ! -f "${stylesheet}" ]; then
     echo "stylesheet not found: ${stylesheet}"
     exit 1
@@ -45,6 +45,15 @@ if [ ! ${result} -eq 0 ]; then
     exit 1
 fi
 
+diarypath=$(jq -r '.path' ${configfile})
+result=$?
+if [ ! ${result} -eq 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    echo "fragment: ${fragment}"
+    exit 1
+fi
+
 diary=$(jq -r '.diary' ${configfile})
 result=$?
 if [ ! ${result} -eq 0 ]; then
@@ -54,7 +63,7 @@ if [ ! ${result} -eq 0 ]; then
     exit 1
 fi
 
-source="${root}/${diary}/metadata/fragments"
+source="${root}/${diarypath}/${diary}/metadata/fragments"
 if [ ! -d "${source}" ]; then
     echo "directory not found: ${source}"
     exit 1
