update with the wordconverter

diff --git a/getJar2 b/getJar2
--- a/getJar2
+++ b/getJar2
@@ -1,30 +1,73 @@
 #!/bin/bash
 
-GROUPID=${1}
+REPOSITORYURL=${1}
+if [ -z "${REPOSITORYURL}" ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "Missing REPOSITORYURL argument"
+    exit 1
+fi
+
+REPOSITORYID=${2}
+if [ -z "${REPOSITORYID}" ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "Missing REPOSITORYID argument"
+    exit 1
+fi
+
+REPOSITORY=${3}
+if [ -z "${REPOSITORY}" ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "Missing REPOSITORY argument"
+    exit 1
+fi
+
+GROUPID=${4}
 if [ -z "${GROUPID}" ]; then
     echo "Error: $0[${LINENO}]"
     echo "Missing GROUPID argument"
     exit 1
 fi
 
-ARTIFACTID=${2}
+ARTIFACTID=${5}
 if [ -z "${ARTIFACTID}" ]; then
     echo "Error: $0[${LINENO}]"
     echo "Missing ARTIFACTID argument"
     exit 1
 fi
 
-VERSION=${3}
+VERSION=${6}
 if [ -z "${VERSION}" ]; then
     echo "Error: $0[${LINENO}]"
     echo "Missing VERSION argument"
     exit 1
 fi
 
-PACKAGING=${4}
+PACKAGING=${7}
 if [ -z "${PACKAGING}" ]; then
     PACKAGING="jar"
 fi
+
+
+
+#*****************************************************************
+# Create the output directory
+#*****************************************************************
+currentDir=$(pwd)
+result=$?
+if [ ! ${result} -eq 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    exit 1
+fi
+
+mkdir -p output/version temp
+result=$?
+if [ ! ${result} -eq 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    exit 1
+fi
+
 
 if [[ "$OSTYPE" == "cygwin" ]]; then
     MVN_HOME=$(cygpath -u "$USERPROFILE")
@@ -34,17 +77,19 @@ fi
 
 filename=${MVN_HOME}/.m2/repository/${GROUPID//.//}/${ARTIFACTID}/${VERSION}/${ARTIFACTID}-${VERSION}.${PACKAGING}
 if [ ! -f "${filename}" ]; then
-    mvn --batch-mode --log-file ./output/output.txt dependency:get -Dartifact=${GROUPID}:${ARTIFACTID}:${VERSION}
+    mvn --batch-mode --log-file output.txt dependency:get -DremoteRepositories=${REPOSITORYURL}/${REPOSITORY} -Dartifact=${GROUPID}:${ARTIFACTID}:${VERSION}
     result=$?
     if [ ! ${result} -eq 0 ]; then
         echo "Error: $0[${LINENO}]"
         echo "result: ${result}"
         echo "----[ output.txt ]--------------------------"
-        cat ./output/output.txt
+        cat output.txt
         echo "----------------------------------------"
         exit 1
     fi
 fi
+
+rm -rf output.txt
 
 if [ ! -f "${filename}" ]; then
     echo "Error: $0[${LINENO}]"
